In [1]:
import numpy as np

# Define the neural network architecture
class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        self.weights1 = np.random.randn(input_size, hidden_size)
        self.weights2 = np.random.randn(hidden_size, hidden_size)
        self.weights3 = np.random.randn(hidden_size, output_size)
    
    def forward(self, X):
        self.hidden1 = np.dot(X, self.weights1)
        self.hidden2 = np.dot(self.hidden1, self.weights2)
        self.output = np.dot(self.hidden2, self.weights3)
        return self.output
    
    def backward(self, X, y, output):
        self.output_error = y - output
        self.output_delta = self.output_error * 0.1
        self.hidden2_error = np.dot(self.output_delta, self.weights3.T)
        self.hidden2_delta = self.hidden2_error * (self.hidden2 > 0)
        self.hidden1_error = np.dot(self.hidden2_delta, self.weights2.T)
        self.hidden1_delta = self.hidden1_error * (self.hidden1 > 0)
        self.weights1 += np.dot(X.T, self.hidden1_delta)
        self.weights2 += np.dot(self.hidden1.T, self.hidden2_delta)
        self.weights3 += np.dot(self.hidden2.T, self.output_delta)

# Define the input, output, and hidden layer sizes
input_size = 2
hidden_size = 4
output_size = 1

# Create the neural network
nn = NeuralNetwork(input_size, hidden_size, output_size)

# Define the training data
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

# Train the neural network
for i in range(10000):
    output = nn.forward(X)
    nn.backward(X, y, output)

# Test the neural network
test_input = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
test_output = nn.forward(test_input)
print(test_output)

[[0.        ]
 [0.33333549]
 [0.33364484]
 [0.66698034]]


In [4]:
import numpy as np

# Define the neural network architecture
class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size, reg_lambda=0.01):
        self.weights1 = np.random.randn(input_size, hidden_size)
        self.weights2 = np.random.randn(hidden_size, hidden_size)
        self.weights3 = np.random.randn(hidden_size, output_size)
        self.reg_lambda = reg_lambda
    
    def forward(self, X):
        self.hidden1 = np.dot(X, self.weights1)
        self.hidden2 = np.dot(self.hidden1, self.weights2)
        self.output = np.dot(self.hidden2, self.weights3)
        return self.output
    
    def backward(self, X, y, output):
        self.output_error = y - output
        self.output_delta = self.output_error * 0.1
        self.hidden2_error = np.dot(self.output_delta, self.weights3.T)
        self.hidden2_delta = self.hidden2_error * (self.hidden2 > 0)
        self.hidden1_error = np.dot(self.hidden2_delta, self.weights2.T)
        self.hidden1_delta = self.hidden1_error * (self.hidden1 > 0)
        self.weights1 += np.dot(X.T, self.hidden1_delta) - self.reg_lambda * self.weights1
        self.weights2 += np.dot(self.hidden1.T, self.hidden2_delta) - self.reg_lambda * self.weights2
        self.weights3 += np.dot(self.hidden2.T, self.output_delta) - self.reg_lambda * self.weights3

# Define the input, output, and hidden layer sizes
input_size = 2
hidden_size = 4
output_size = 1

# Create the neural network
nn = NeuralNetwork(input_size, hidden_size, output_size, reg_lambda=0.01)

# Define the training data
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

# Train the neural network
for i in range(10000):
    output = nn.forward(X)
    nn.backward(X, y, output)

# Test the neural network
test_input = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
test_output = nn.forward(test_input)
print(test_output)

[[ 0.        ]
 [-0.16072753]
 [ 0.35897574]
 [ 0.19824821]]


In [3]:
import numpy as np

# Define the input and output data
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

# Define the weights and biases of the neural network
W1 = np.random.randn(2, 4)
b1 = np.zeros((1, 4))
W2 = np.random.randn(4, 1)
b2 = np.zeros((1, 1))

# Define the activation function (sigmoid)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define the derivative of the activation function (sigmoid)
def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

# Define the forward pass of the neural network
def forward(X, W1, b1, W2, b2):
    Z1 = np.dot(X, W1) + b1
    A1 = sigmoid(Z1)
    Z2 = np.dot(A1, W2) + b2
    A2 = sigmoid(Z2)
    return A1, A2

# Define the backward pass of the neural network
def backward(X, y, A1, A2, W1, W2):
    error = A2 - y
    dZ2 = error * sigmoid_derivative(A2)
    dW2 = np.dot(A1.T, dZ2)
    db2 = np.sum(dZ2, axis=0, keepdims=True)
    dZ1 = np.dot(dZ2, W2.T) * sigmoid_derivative(A1)
    dW1 = np.dot(X.T, dZ1)
    db1 = np.sum(dZ1, axis=0)
    return dW1, db1, dW2, db2

# Define the training loop of the neural network
learning_rate = 0.1
for i in range(10000):
    A1, A2 = forward(X, W1, b1, W2, b2)
    dW1, db1, dW2, db2 = backward(X, y, A1, A2, W1, W2)
    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1
    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2

# Compute the final activations and predictions of the neural network
A1, A2 = forward(X, W1, b1, W2, b2)
predictions = (A2 > 0.5).astype(int)

# Print the results
print('Input data:\n', X)
print('Output data:\n', y)
print('Final activations:\n', A2)
print('Predictions:\n', predictions)

Input data:
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Output data:
 [[0]
 [1]
 [1]
 [0]]
Final activations:
 [[0.10423613]
 [0.86423027]
 [0.85961803]
 [0.12362304]]
Predictions:
 [[0]
 [1]
 [1]
 [0]]
